name: Build RustDesk macOS Universal

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      FLUTTER_DIR: flutter          # pubspec.yaml 所在目录
      APP_NAME: RustDesk
      FLUTTER_SDK: "3.24.4"         # 代码当前可编译的最后一个版本

    steps:
    # 1️⃣ 取代码
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2️⃣ 安装指定版本的 Flutter
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ env.FLUTTER_SDK }}   # <-- 正确写法

    # 3️⃣ 安装并执行 flutter_rust_bridge codegen
    - name: Generate Dart ↔ Rust 桥接文件
      run: |
        dart pub global activate flutter_rust_bridge_codegen 1.80.1
        export PATH="$HOME/.pub-cache/bin:$PATH"
        cd ${{ github.workspace }}/${{ env.FLUTTER_DIR }}
        flutter pub get
        flutter_rust_bridge_codegen \
          --rust-input ../src/flutter_ffi.rs \
          --dart-output lib/generated_bridge.dart

    # 4️⃣ CocoaPods
    - name: Pod install (arm64 + x86_64)
      run: |
        cd ${{ github.workspace }}/${{ env.FLUTTER_DIR }}
        arch -arm64 pod install   --project-directory=macos
        arch -x86_64 pod install --project-directory=macos || true   # x86 机器才会真跑

    # 5️⃣ 编译 macOS
    - name: flutter build macos
      run: |
        cd ${{ github.workspace }}/${{ env.FLUTTER_DIR }}
        flutter build macos --release --dart-define=BUNDLE_MODE=true

    # 6️⃣ (可选) Codesign / Lipo 等操作，这里省略
