name: Build RustDesk macOS Universal

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    env:
      FLUTTER_DIR: flutter
      FLUTTER_SDK: 3.24.4

    steps:
    # 1. Checkout
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2. Setup Flutter
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ env.FLUTTER_SDK }}

    # 3. Install deps & 生成桥接代码
    - name: Install & Codegen
      run: |
        cd ${{ github.workspace }}/${{ env.FLUTTER_DIR }}
        flutter pub get
        flutter pub run flutter_rust_bridge_codegen \
          --rust-input ../src/flutter_ffi.rs \
          --dart-output lib/generated_bridge.dart

    # 4. CocoaPods 安装（ARM + Intel）
    - name: Pod install
      run: |
        cd ${{ github.workspace }}/${{ env.FLUTTER_DIR }}
        arch -arm64 pod install --project-directory=macos
        arch -x86_64 pod install --project-directory=macos || true

    # 5. Build macOS
    - name: Build macOS release
      run: |
        cd ${{ github.workspace }}/${{ env.FLUTTER_DIR }}
        flutter clean
        flutter build macos --release --dart-define=BUNDLE_MODE=true

    # 6.（可选）后续 lipo、codesign、打包等
